window.PORTFOLIO_DATA = {
  name: "Collins Warutumo",
  tagline: "Cybersecurity Engineer | Full Stack Developer",
  about: "Certified cybersecurity and IS audit professional with 10+ years of hands-on experience in application security, cyber assurance, penetration testing, full-stack development, and enterprise workflow automation. Holds an MSc in Information Systems Security (Digital Forensics major) with CISA, CISM, and CEH credentials — combining engineering depth with audit-grade rigour across fintech and enterprise platforms.",
  location: "Nairobi, Kenya",
  contact: {
    linkedin: "https://www.linkedin.com/in/waruts"
  },
  skills: [
    "Vulnerability Management", "Penetration Testing (VAPT)", "Information Security Audits", "Risk Management", "Governance", "Compliance", "Digital Forensics", "Incident Response", "Security Operations", "Network Security", "Cloud Security", "Data Protection", "Ethical Hacking", "Threat Modelling", "Internal Controls", "Identity & Access Management", "Zero Trust Architecture", "OWASP", "Java (Spring Boot)", "Python", "JavaScript", "PHP (Laravel)", "SQL", "API Development (REST)", "Microservices Architecture", "Full Stack Development", "Temporal Workflows", "Apigee Hybrid (GCP)", "Kafka (Event Streaming)", "Redis", "PostgreSQL", "MySQL", "Vue.js", "Node.js", "AWS (EKS)", "Kubernetes", "Docker", "OpenShift", "CI/CD (Jenkins / FluxCD)", "GitOps", "FluxCD", "ArgoCD (Conceptual)", "Helm", "Workflow Automation", "Process Orchestration", "Linux Administration", "SonarQube", "Figma", "Streamlit", "Pusher", "SAP ERP", "Hibernate / JPA", "Spring Security", "Generative AI (Security Automation)", "LLM / Agentic AI (Experimentation)", "MLOps (Conceptual)", "ISO 27001", "NIST CSF", "COBIT", "PCI DSS", "GDPR", "CIS Controls", "ISO 22301", "GSMA Security", "SIEM / XDR", "Burp Suite", "Nmap", "Nessus", "Audit Reporting", "Regulatory Compliance"
  ],
  certifications: [
    "Certified Information Systems Auditor (CISA) — ISACA #1163766",
    "Certified Information Security Manager (CISM) — ISACA #1163766",
    "Certified Ethical Hacker (CEH) — EC-Council #ECC2483150796",
    "Project Management Professional (PMP) — In Progress"
  ],
  projects: [
    {
      name: "MySacco — Telco FOSA Admin Platform",
      description: "Multi-tenant FOSA admin platform empowering 50+ Saccos serving 10M+ members. G3 M-PESA float management integrated with the telco's core G3 M-PESA system, real-time depletion alerting through Kafka event-driven microservices, and analytics streamed into Apache Doris and ClickHouse for burn-rate calculation, expected depletion prediction, and usage trends. Includes configurable transactional charges, favourites, lead generation, and FAQs.",
      url: "https://channels.mysacco.safaricom.co.ke", category: "software", tech: ["Java (Spring Boot)", "Apache Kafka", "Apache Doris", "ClickHouse", "Kubernetes", "AWS", "PostgreSQL", "Redis", "M-PESA G3 Integration", "Multi-tenancy", "Reactive Microservices"]
    },
    { name: "Order Orchestration & Workflow Automation", description: "Designed and delivered an enterprise-grade Gen AI order orchestration engine powering a B2B Marketplace. Built on Temporal (Java) with Spring Boot microservices, GitOps CI/CD on AWS EKS, and SonarQube quality gates. Drove 80% enterprise sales growth and 75% revenue improvement through workflow automation.", url: "https://business.safaricom.co.ke/marketplace", category: "software", tech: ["Java (Spring Boot)", "Temporal", "PostgreSQL", "Redis", "AWS EKS", "Kubernetes", "Jenkins", "FluxCD", "SonarQube"] },
    { name: "Digital Forensics Chain of Custody System", description: "MSc dissertation research and system implementation for preservation of digital evidence integrity, directly applicable to forensic audit and incident investigation workflows.", url: "https://opac.library.strathmore.edu/bib/314908", category: "cyber", tech: ["Laravel", "Digital Forensics", "Evidence Management", "MySQL"] },
    { name: "Apigee Hybrid API Gateway Management", description: "Managed Apigee Hybrid (GCP) deployment with Kubernetes-hosted runtime plane, covering API lifecycle governance, OAuth 2.0, mTLS, rate limiting, and developer onboarding.", url: "", category: "software", tech: ["Apigee Hybrid (GCP)", "Kubernetes", "OAuth 2.0", "mTLS", "API Security", "GCP"] },
    { name: "Multi-Tenant Financial Services APIs", description: "Built scalable multi-tenant APIs for My One App, My County, and My Sacco, enabling secure access to financial and community services through a unified governed platform architecture.", url: "", category: "software", tech: ["Spring Boot", "Microservices", "REST APIs", "PostgreSQL", "Multi-tenancy"] },
    { name: "PII Compliance Automation & Cyber Assurance", description: "Built automated scripts and cron jobs for PII violation detection and encryption standard enforcement across enterprise fintech platforms serving 20M+ monthly users, using AI tooling to guide secure coding practices.", url: "", category: "cyber", tech: ["Python", "Bash Scripting", "Cron Jobs", "Data Protection Act", "ISO 27001", "AI-Assisted Security"] },
    { name: "Reusable Notification Microservices", description: "Reusable cross-team microservices supporting 5M+ monthly traffic and transactional email notifications across enterprise portals.", url: "https://business.safaricom.co.ke/track-order", category: "software", tech: ["Java (Spring Boot)", "Microservices", "REST APIs", "Redis", "PostgreSQL"] },
    { name: "Leads Microservices — MySacco & Business Hub", description: "Lead management microservices covering prospect capture, qualification, onboarding, lead-to-opportunity conversion, CRM integration, and enterprise revenue growth.", url: "https://business.safaricom.co.ke/marketplace", category: "software", tech: ["Java (Spring Boot)", "Microservices", "REST APIs", "PostgreSQL", "Redis", "CRM Integration"] },
    { name: "The Actuarial Society of Kenya Portal", description: "Membership management and CPD tracking platform with automated event registration, compliance monitoring, and payments — achieving 60% revenue growth and 70% operational efficiency improvement.", url: "https://www.actuarieskenya.or.ke", category: "software", tech: ["Laravel", "WordPress", "MySQL", "Vue.js", "Payment Integration"] },
    { name: "Café Payment & Customer Management System", description: "Real-time payment and customer management system integrated with NCBA, using Pusher-based live transaction state management.", url: "https://smilescafe.co.ke", category: "software", tech: ["Vue.js", "Laravel", "Vuex", "Vite", "Pusher", "MySQL"] },
    { name: "Telegram FastBuddy Bot", description: "Healthy living intermittent fasting bot that tracks fasts and shares personalised guidance.", url: "https://t.me/i_fast_bot", github: "https://github.com/waruts1/fastbuddy", category: "software", tech: ["Flask", "Python", "SQL", "Telegram API", "CI/CD"] },
    { name: "Jiji Vehicle Dataset Analysis", description: "Data analysis and visualisation of vehicle listings based on price, make, model, and year of manufacture.", url: "", github: "https://github.com/waruts1/streamlit-jiji-vehicles-visualization", category: "software", tech: ["Python", "Streamlit", "Jupyter Notebook", "Pandas", "SQL"] }
  ],
  experience: [
    { title: "Cyber Security Engineer", company: "Telco", category: "cyber", location: "Nairobi, Kenya", dates: "January 2026 – Present", responsibilities: ["Conducting risk-based information security audits and assurance reviews across applications, infrastructure, and operational processes", "Performing vulnerability assessments and penetration tests across web applications, APIs, and cloud environments", "Assessing IAM/PAM controls, encryption standards, and data protection compliance", "Delivering structured assurance reports to leadership and regulators", "Leveraging AI tooling and automation to scale security controls"], achievements: ["Built automated PII detection scripts enforcing encryption and access standards across platforms serving 20M+ monthly users", "Implemented monitoring and anomaly detection mechanisms enabling early identification of unauthorised access patterns", "Deployed AI-assisted developer security guidance programme improving secure coding adoption"], skills: ["Information Security Audits", "VAPT", "Risk Management", "Compliance & Governance", "Identity & Access Management", "Cloud Security (AWS)", "Incident Response", "Digital Forensics", "Penetration Testing", "Security Operations", "Network Security", "Automation (Python / CI/CD)", "ISO 27001", "NIST CSF"] },
    { title: "Full Stack Developer", company: "Telco", category: "software", location: "Nairobi, Kenya", dates: "July 2021 – December 2025", responsibilities: ["Designed, developed, tested, and documented enterprise REST APIs using Java Spring Boot and microservices architecture", "Managed Apigee Hybrid (GCP) API gateway", "Integrated enterprise applications with CRM, CBS Billing, and NCBA", "Built GitOps CI/CD pipelines using FluxCD, Jenkins, AWS EKS, and Kubernetes", "Implemented Redis-driven event streaming"], achievements: ["Delivered Zidisha recommendation engine serving 1M+ SME agents and 20M+ monthly customers — generating 19M+ monthly revenue", "Built reusable notification microservice handling 5M+ monthly traffic", "Engineered 2 SaaS products delivering 50% revenue boost and 30% customer base expansion", "Delivered 20+ analytical dashboards"], skills: ["Java (Spring Boot)", "Apigee Hybrid (GCP)", "REST API Development", "Microservices Architecture", "Redis", "PostgreSQL", "AWS (EKS)", "Kubernetes", "CI/CD (Jenkins / FluxCD)", "GitOps", "Vue.js", "Authentication & Authorisation", "Data Protection Act Compliance", "SQL"] },
    { title: "Process Automation Engineer", company: "Telco", category: "software", location: "Nairobi, Kenya", dates: "November 2020 – October 2021", responsibilities: ["Architected durable workflow orchestration using Temporal (Java), including long-running processes, saga patterns, retries, and activity workers", "Designed and tested enterprise-grade workflows for Gen AI order orchestration and SaaS delivery", "Audited workflow performance, data integrity, and process compliance"], achievements: ["Built Kazuri process engine powering B2B Marketplace — driving 80% enterprise sales growth and 30% customer onboarding improvement", "Delivered order orchestration workflow achieving 75% revenue growth through resilient fault-tolerant automation"], skills: ["Temporal (Java)", "Workflow Orchestration", "Spring Boot", "Process Automation", "API Integration", "Python (Scripting)", "CI/CD", "AWS", "Kubernetes", "Audit & Testing"] },
    { title: "Full Stack Developer", company: "@iLabAfrica — Strathmore University Research Centre", category: "software", location: "Nairobi, Kenya", dates: "August 2018 – October 2020", responsibilities: ["Delivered full stack features across WordPress, Django, Laravel, and Vue.js", "Conducted application security reviews and vulnerability assessments", "Designed Figma prototypes"], achievements: ["Delivered Actuarial Society membership and CPD platform — 60% revenue growth and 70% operational efficiency improvement", "Implemented authentication and security controls for IMLU Incident Management System", "Completed QA and security assurance for KAM Portal", "Built iLabPay payment gateway"], skills: ["Full Stack Development", "Laravel", "Django", "Vue.js", "WordPress", "Application Security", "VAPT", "Figma", "Authentication", "SQL", "QA & Testing"] },
    { title: "Cyber Security Engineer", company: "Strathmore University — iLabAfrica Research Centre", category: "cyber", location: "Nairobi, Kenya", dates: "May 2016 – July 2018", responsibilities: ["Implemented automated security tests and information security controls", "Conducted information security research including MSc dissertation on Digital Forensics Chain of Custody", "Performed IS audits and implemented information governance frameworks", "Designed secure architectures"], achievements: ["MSc research on Digital Evidence Chain of Custody published at Strathmore University Library", "Established security review processes for iLabPay, WILD Mara, MSALM, and Ushahidi"], skills: ["Information Security", "Digital Forensics", "Security Testing", "Automated Security Tests", "Information Governance", "IS Audits", "Risk Management", "Incident Response", "Compliance", "Secure SDLC"] },
    { title: "ERP Support Engineer", company: "Kenya Power", category: "software", location: "Nakuru, Kenya", dates: "January 2015 – December 2015", responsibilities: ["SAP ERP configuration, support, and administration", "Computer hardware configuration and troubleshooting", "User training and technical support"], skills: ["SAP ERP", "ERP Support & Configuration", "System Troubleshooting", "Hardware Configuration", "User Training & Support", "SQL (Basic)"] }
  ],
  education: [
    { degree: "MSc Information Systems Security — Digital Forensics Major", institution: "Strathmore University", detail: "Dissertation: Digital Preservation of Digital Evidence Chain of Custody" },
    { degree: "BSc Business and Information Technology — Second Upper Class", institution: "Strathmore University" },
    { degree: "CISA & CISM Certification Programme", institution: "ISACA" },
    { degree: "Certified Ethical Hacker (CEH)", institution: "EC-Council" }
  ]
};