#!/usr/bin/env node
/*
 * Encrypts the portfolio content for publishing.
 *
 *   node scripts/profile-crypto.mjs encrypt   profile.data.js     -> profile.data.enc.js
 *   node scripts/profile-crypto.mjs decrypt   profile.data.enc.js -> profile.data.js
 *
 * profile.data.js is the readable source you edit. It is git-ignored and never
 * published; run `encrypt` after every edit and commit profile.data.enc.js.
 * `decrypt` rebuilds the source from the published file if you lose it.
 *
 * What this does and does not protect: the published file is AES-256-GCM
 * ciphertext, so the content is not readable in the repository, in "view
 * source", or by scrapers that fetch the file. The page must decrypt it to
 * show it, so the key ships in profile.js — anyone who runs the page can
 * still read what it displays. Do not put anything here that must stay secret.
 */
import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(root, 'profile.data.js');
const PUBLISHED = join(root, 'profile.data.enc.js');
const RENDERER = join(root, 'profile.js');

function loadKey() {
  const match = readFileSync(RENDERER, 'utf8').match(/const PROFILE_KEY = '([A-Za-z0-9+/=]+)';/);
  const key = match ? Buffer.from(match[1], 'base64') : null;
  if (!key || key.length !== 32) throw new Error('PROFILE_KEY (32 bytes, base64) not found in profile.js');
  return key;
}

// Both files are scripts that assign one property on `window`
function readWindowValue(file, name) {
  const sandbox = { window: {} };
  vm.runInNewContext(readFileSync(file, 'utf8'), sandbox, { filename: file });
  if (sandbox.window[name] === undefined) throw new Error(`${file} does not set window.${name}`);
  return sandbox.window[name];
}

function encrypt() {
  const profile = readWindowValue(SOURCE, 'PORTFOLIO_DATA');
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', loadKey(), iv);
  const sealed = Buffer.concat([cipher.update(JSON.stringify(profile), 'utf8'), cipher.final(), cipher.getAuthTag()]);
  const published = { v: 1, iv: iv.toString('base64'), data: sealed.toString('base64') };
  writeFileSync(PUBLISHED, [
    '// Generated by scripts/profile-crypto.mjs — do not edit. Edit profile.data.js and re-run `encrypt`.',
    `window.PORTFOLIO_DATA_ENC = ${JSON.stringify(published)};`,
    ''
  ].join('\n'));
  console.log(`Encrypted ${Object.keys(profile).length} profile fields -> profile.data.enc.js`);
}

function decrypt() {
  const published = readWindowValue(PUBLISHED, 'PORTFOLIO_DATA_ENC');
  const sealed = Buffer.from(published.data, 'base64');
  const decipher = createDecipheriv('aes-256-gcm', loadKey(), Buffer.from(published.iv, 'base64'));
  decipher.setAuthTag(sealed.subarray(sealed.length - 16));
  const json = Buffer.concat([decipher.update(sealed.subarray(0, sealed.length - 16)), decipher.final()]).toString('utf8');
  writeFileSync(SOURCE, `window.PORTFOLIO_DATA = ${JSON.stringify(JSON.parse(json), null, 2)};\n`);
  console.log('Decrypted profile.data.enc.js -> profile.data.js');
}

const command = process.argv[2];
if (command === 'encrypt') encrypt();
else if (command === 'decrypt') decrypt();
else {
  console.error('Usage: node scripts/profile-crypto.mjs <encrypt|decrypt>');
  process.exit(1);
}
